### ISSUE TITLE
Purpose of nodejs/CTC

### ISSUE THREAD

**Issue by rvagg** [nodejs/CTC#1]
@nodejs/collaborators I'm not sure if this is clear enough but here's what's on the README, please file a PR if you think it can be improved. Hopefully the next series of issues will help clarify the purpose.

---

A repository for dealing with meta technical matters related to the Node.js project. For non-technical organizational matters please see the [TSC](https://github.com/nodejs/CTC) repository.

---

**This repository is _primarily_ for the use of the Node.js core project Collaborators group and the CTC**. If you are not part of the Collaborator group, please confer with a member of the CTC (listed on the Node.js [README](https://github.com/nodejs/node#ctc-core-technical-committee)) before opening a new discussion here.

**_Because this is a space for Collaborators and the TSC to discuss internal concerns, issues are likely to be locked and limited to these groups as soon as they become too noisy. There are better forums for public input (see below).**_

---

Meta technical matters to be discussed here include, but are not limited to:
- Future-facing topics that are likely to feed into a [roadmap](https://github.com/nodejs/roadmap/) for Node.js at some point, without being so far forward that they belong in [Node.js NG](https://github.com/nodejs/ng)
- Issues that Node.js needs to begin considering before there is a something to actually deal with, e.g. proposals being prepared at TC39 that may impact Node.js
- Large topics that don't yet have a concrete proposal ready to file as an [EP](https://github.com/nodejs/node-eps) and need further refinement via discussion
- Technical organization concerns that are difficult to discuss in [nodejs/node](https://github.com/nodejs/node), e.g. the relationship between the /docs/ directory and the Documentation Working Group or Streams code in core and the Streams Working Group.

---
- If you have a **concrete proposal for the enhancement of Node.js**, you can file it for discussion at https://github.com/nodejs/node-eps
- If you are **looking for Node.js help**, please file an issue at https://github.com/nodejs/help
- If you wish to **file a bug report about Node.js or have a fix prepared**, please file it at https://github.com/nodejs/node
- **Ideas and proposals from the public for the future of Node.js** can be discussed in [roadmap](https://github.com/nodejs/roadmap/) or [NG](https://github.com/nodejs/ng).

**Comment by vkurchatkin** [comment]
> Core Technical Team (CTC)

Typo?

**Comment by rvagg** [comment]
blerh, yes, fixing, thanks

**Comment by benjamingr** [comment]
If I want to being an issue to the CTC's attention would this repo be a good place to open it?

(I specifically mean issues that are about the project's technical direction and not general user feedback)

**Comment by benjamingr** [comment]
> Issues that Node.js needs to begin considering before there is a something to actually deal with, e.g. proposals being prepared at TC39 that may impact Node.js

Never mind, it sort of falls under that. I'll leave my comment in case future readers find it useful.

**Comment by Trott** [comment]
I dislike "meta technical" because it seems unclear to me, but I'm also having trouble coming up with a better phrase, so... 
¯\_(ツ)_/¯

Other than that, I like it.

**Comment by joshgav** [comment]
Maybe we should update https://nodejs.org/en/about/working-groups/ and/or add a directory of GH repos somewhere.

**Comment by Trott** [comment]
Discussion appears to have run its course on this. Closing. Feel free to re-open or comment if you think this should remain open.
