### ISSUE TITLE
Next V8 - CTC call

### ISSUE THREAD

**Issue by hashseed** [nodejs/CTC#101]
[Last](https://github.com/nodejs/CTC/issues/62) [two](https://github.com/nodejs/CTC/issues/76) calls were very productive, and I think it makes sense to repeat. Some considerations though:

- I'm on leave between May 1st and July 8th. I could still organize the next call, but that would either be fairly short notice, or I won't be able to attend (which is fine.
- There is JSConf EU coming up. A few V8 team members are going to show up, a subset of which will also give talks. I had the impression the same applies to part of the CTC. Maybe it makes sense to set up a face to face meeting instead? @fhinkel is there anything of the sort planned?
- Agenda items? Some of the previous agenda items were
  - GYP/GN
  - Debug context deprecation
  - Launch of V8's new compiler pipeline: benchmarks, how to contribute to Node
  - Performance bottlenecks (which we have yet to act upon, yielding priority to the new pipeline though)

**Comment by fhinkel** [comment]
There's a two day Node collaborator meeting before JSConf EU.

**Comment by addaleax** [comment]
Yes, any interested V8 people – not limited to Node collaborators – would be *very* much invited to attend that. Also, I think @MylesBorins was considering organizing a CTC + V8 team dinner on May 5.

**Comment by hashseed** [comment]
Alright. I'll close this issue and simply assume that @MylesBorins will organize something awesome.

**Comment by mhdawson** [comment]
Looking forward to it :)
