### ISSUE TITLE
How about to update the name of issue label for V8?

### ISSUE THREAD

**Issue by watilde** [nodejs/CTC#103]
Currently, we're labelling `V8` related issues as `V8`, but it potentially makes a confusion since Node.js v8.0.0 is coming around the corner. It will be necessary to clear whether `V8` or `v8.x` or `V8` in `v8.x` in some discussions.

Here is an actual example to imagine:
<img width="298" alt="2017-04-14 16 15 49" src="https://cloud.githubusercontent.com/assets/1716463/25045669/aa3f99ae-212d-11e7-873e-aa86ecbcedad.png">

So that I'd suggest using the other name for V8 label:
+ `V8 JavaScript Engine`: used in the [official blog](https://v8project.blogspot.com/)
+ `Chrome V8`: used in the [official website](https://developers.google.com/v8/)

**Comment by addaleax** [comment]
How about `V8` → `V8 Engine`?

**Comment by watilde** [comment]
^The shortened name would be better :)

**Comment by andrasq** [comment]
In my own notes I've kept the short `V8` for the engine, am using `v8.x` for the version.

**Comment by addaleax** [comment]
Fwiw that’s also how we currently use the labels. But if renaming the `V8` label might help reduce confusion, why not?

**Comment by MylesBorins** [comment]
I thought we were dropping the `v` from version
v8.x -> 8.x

**Comment by jasnell** [comment]
Yep, we are. The branches will still have the `v` for sake of consistency with the other release branches, but the `v` will be removed from the changelogs and messaging.

**Comment by addaleax** [comment]
Renaming labels is cheap, so it’s called `V8 Engine` now. If somebody else has better suggestions, we can just re-rename. :)

**Comment by watilde** [comment]
Closing as resolved, but what @addaleax said.

Thanks!

**Comment by gibfahn** [comment]
Now the `github-bot` is auto-labelling PRs, if we change label names we need to update the bot.

Still +1 on this change, just noting for future reference.
