### ISSUE TITLE
`util.callbackify` for async functions

### ISSUE THREAD

**Issue by benjamingr** [nodejs/CTC#109]
Hey,

From https://github.com/nodejs/promises/issues/6 originally, but seeing that `util.promisify` is finally in sight, I think this might be worth proposing too.

I propose that for compatibility reasons, and so that callback users using Node can keep working with their tooling to add a `util.callbackify` function that converts an async function to a callback taking function.

For example:

```js
async function foo() {
  let data1 = await promiseApi(..);
  let data2 = await promiseApiOther(data1);
  return result;
}
const foo2 = util.callbackify(foo);
foo2(function(err, data) {
  // error here if foo threw
  // use data here
});
```

This is likely faster in core, and would enable seamless integration of async functions into callback APIs and code bases. Seeing as we're not going to make a promisified core any time soon - this is beneficial for interoping between code bases using callbacks and async functions together. 

How do @nodejs/collaborators feel about this?

**Comment by mcollina** [comment]
I think we need this if we want to ship promisify.

**Comment by Qard** [comment]
:+1: from me. Regardless of how core feels about promises and async/await, userland *will* use them, so we need to ensure interop works well.

**Comment by cjihrig** [comment]
I think it makes sense if promisify makes it in.

**Comment by vkurchatkin** [comment]
-1 unless we have something to offer in terms of performance

**Comment by bnoordhuis** [comment]
Someone has to say it: `s/toCallback/callbackify/`

**Comment by evanlucas** [comment]
> Someone has to say it: `s/toCallback/callbackify/`

Yea, can we be consistent?

**Comment by benjamingr** [comment]
@bnoordhuis @evanlucas this issue was mostly to see if there is interest - I've amended to `callbackify`.

**Comment by refack** [comment]
At the moment I see 20 👍 so
😀me
![image](https://cloud.githubusercontent.com/assets/96947/25449227/2417a262-2a89-11e7-872d-4c897f7cca5e.png)gauntlet
🏋️‍Picking up

(ouch! my back 😖)

**Comment by refack** [comment]
@not-an-aardvark I'm working on a PR, finishing some tests and will upload tomorrow for you'll to review...

**Comment by eljefedelrodeodeljefe** [comment]
I'd be happy if we could push https://github.com/nodejs/node/pull/12712 forward.

**Comment by refack** [comment]
I believe this could be closed now that https://github.com/nodejs/node/pull/12712/commits/af3aa682ac534bb55765f5fef2755a88e5ff2580 landed

**Comment by benjamingr** [comment]
Sweet! Thanks a lot @refack :)
