### ISSUE TITLE
When do we stop landing semver major changes prior to a Major release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/CTC#11]
When we cut v6 we landed a number of semver major changes in the days leading to the release, this resulted in quite a bit of ecosystem pain.

Do we want to set a scheduled time in which we will lock semver major changes on master?

Do we want to do some sort of alpha / beta / rc release process in the months leading up to the release?

**Comment by jasnell** [comment]
This is really a question for the main repo since the cut off happens long before the branch moves to LTS. That said, my vote is one month with a rigorous candidate release cycle. Exceptions granted only with CTC discussion and approval.

**Comment by mhdawson** [comment]
I'd agree that a month seems reasonable.  We probably also need to back things out quickly if there are problems as opposed to trying to fix them at that point as well.

**Comment by evanlucas** [comment]
@mhdawson I totally agree. I think we should revert vs trying to fix quickly, since quick fixes don't always happen that quickly

**Comment by Trott** [comment]
Closing. Feel free to re-open if you think there's more to discuss or that there isn't a more appropriate place for the conversation!

**Comment by refack** [comment]
Just for the books for node8 the decision was 21 days https://github.com/nodejs/node/pull/12220#issuecomment-296682211
<sub>personally to me it seems reasonable</sub>
