### ISSUE TITLE
Protect release branches

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/CTC#116]
Should we limit pushing to release branches to release team? I think so!

I think we should protect all release .x branches and only allow release team to push. This will not stop Owners + Admins from pushing FWIW

**Comment by jasnell** [comment]
SGTM

**Comment by cjihrig** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by refack** [comment]
@MylesBorins dup of https://github.com/nodejs/CTC/issues/129?

**Comment by MylesBorins** [comment]
This was not done... we only protected staging branches (which I think we can revert)

**Comment by gibfahn** [comment]
> This was not done... we only protected staging branches (which I think we can revert)

+1 to unprotecting staging branches (because we often need to force-push to them) and protecting release branches.

**Comment by gibfahn** [comment]
Note: there are `SGTM`s from @mcollina and @evanlucas in https://github.com/nodejs/CTC/issues/129

**Comment by MylesBorins** [comment]
This is implemented. All release branches are now locked to the release team (including admins). Staging is no longer protected
