### ISSUE TITLE
Suggested change for Stand Up

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/CTC#119]
I think it might be more useful for the CTC standup to be organized by working groups / sub systems. Thoughts?

edit:

This can be used for external communications + increased visibility

**Comment by joshgav** [comment]
Perhaps a WG-oriented standup should be part of TSC meetings?

**Comment by Trott** [comment]
I like the idea. I'm not sure of the details of how it would work. Do you have anything specific in mind on how it would work?

**Comment by ChALkeR** [comment]
I don't think that I undersand this proposal without a concrete example.
@MylesBorins could you provide an example of how would any previous standup look like in this format?

**Comment by mcollina** [comment]
Either CTC or TSC is fine. Do we have 100% wg coverage in the TSC? Should we ask someone from each wg to drop a couple of lines before each meeting?

**Comment by mhdawson** [comment]
Is the proposal to drop the individual stand up ? I think that would make sense to me even if we don't replace it with anything else.  Adding it into the minutes in advance seems like enough to me and it would eliminate the time we spend going through it.  

I'm also thinking we can probably also drop the review of the previous meeting.  I don't think we have seen that generate additional conversation.

**Comment by MylesBorins** [comment]
The proposal is indeed to drop the individual standup and replace it with
the wg standup. I think this is a good way to let people know what is going
on in the project (without looking at a doc).

**Comment by jasnell** [comment]
+1 ... I have some larger changes that I'm working on a proposal for. In the meantime, this would definitely be good. The individual standup is largely useless.

**Comment by joshgav** [comment]
I think it would be helpful to have an open part of the meeting for sharing items we think would be of interest to the technical group, I use the CTC standup for that occasionally. Perhaps we can make that part of the Q&A/Other section at the end.

**Comment by joshgav** [comment]
The [TSC's job](https://github.com/nodejs/TSC/blob/master/README.md#tsc-scope) is to support the CTC and WGs and I think a weekly update/standup would facilitate doing that job better. Since the CTC only manages a subset of WG's, I think it would be most efficient for the TSC to manage this for all WG's and the CTC too. I'll open a corresponding issue in nodejs/TSC to discuss and if agreed formulate a plan.

By managing this from the TSC we can also free up CTC to stay focused on core, which is important!

**Comment by joshgav** [comment]
@joshgav

> I'll open a corresponding issue in nodejs/TSC to discuss and if agreed formulate a plan.

Actually https://github.com/nodejs/TSC/issues/109 is already open, and @jasnell ([comment](https://github.com/nodejs/TSC/issues/109#issuecomment-294587337)) has been thinking about this too :). Will continue the discussion there.

**Comment by jasnell** [comment]
The CTC skipped the standup on today's call without any objections being raised. The meeting was rather productive. I'm happy with leaving this to the chair's discretion (cc @Trott) but I think it's pretty well settled at this point.

**Comment by Trott** [comment]
> I think it's pretty well settled at this point.

@jasnell If I'm understanding correctly:

* CTC will have a moment at the beginning for anyone to mention anything they want to sort of announce to other CTC members or to the world in general. (Might be a good idea to move this to the end of the meeting rather than the start but that's a detail.)

* TSC will have a WG-driven standup.

Does that sound about right?

**Comment by jasnell** [comment]
Yes. That is the intent. With the caveat that the tsc currently does not have great wg coverage. Or, at least, it's not clear if we do

**Comment by nebrius** [comment]
> Yes. That is the intent. With the caveat that the tsc currently does not have great wg coverage. Or, at least, it's not clear if we do

I'm fairly certain we don't...if nothing else I feel like we don't have great insight into whether or not we do, which is an issue in and of itself.

**Comment by MylesBorins** [comment]
ATM I don't think it really makes sense to live in the TSC, the stakeholders are not there

**Comment by mhdawson** [comment]
So these are the working groups based on the current CTC readme:

    Website
    Streams
    Build (coverage -> Rod, Michael)
    Diagnostics (coverage -Josh, I'm also ramping up involvement)
    i18n (covers translations)
    Evangelism  (does this fit with community commitee ?)
    Docker
    Addon API  (coverage -> Ben).  There is also the question of whether the the api WG that was never fully chartered should be pulled in.  If that was the case we'd have more coverage.
    Benchmarking (coverage -> Michael)
    Post-mortem (coverage -> Michael
    Intl - (main participant is Stephen Loomis)
    Documentation (being de-chartered)
    Testing (being de-chartered) - do think there is a gap here.
    LTS (being chartered, coverage Michael, James)

**Comment by mhdawson** [comment]
So we have a few gaps in coverage but I don't see that's been the problem.  Its more that we have not made it a priority to ask work groups for updates or if they need help.

**Comment by jasnell** [comment]
Aside from that, we have not made it a priority to ensure that decisions that are made reflect the consensus of the WGs. Rather, we tend to make decisions based on the individual opinions of people who just happen to overlap coverage with various WGs. That's a bit of a problem.

**Comment by Trott** [comment]
We stopped doing standups altogether some time ago in the CTC. Not sure if we're still doing it in TSC meetings. In any event, this issue has been inactive for a while and this repository is now obsolete. I'm going to close this, but feel free to open another issue in a relevant active repository (TSC perhaps?) and include a link back to this issue if this is a subject that should receive continued attention.
