### ISSUE TITLE
FOSSA?

### ISSUE THREAD

**Issue by mikeal** [nodejs/CTC#124]
This looks pretty useful, could automate some of the concerns we've had over licenses.

http://fossa.io/

**Comment by jasnell** [comment]
This looks good but I feel strongly that there's a missed [Fozzy The Bear](https://en.wikipedia.org/wiki/Fozzie_Bear) joke opportunity here.

**Comment by Trott** [comment]
This issue has been inactive for a while and this repository is now obsolete. I'm going to close this, but feel free to open another issue in a relevant active repository (TSC perhaps?) and include a link back to this issue if this is a subject that should receive continued attention.
