### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by jasnell** [nodejs/CTC#13]
Even tho we have implemented a stable and reliable LTS, follow semver closely, pace out our breaking changes every six months, and have a fairly stable current, require CTC sign off for breaking changes, and have started better communicating publicly about breaking changes there's a perception that if we happen to land _any_ breaking changes in master we've "broken the ecosystem" and have done something bad. This has been particularly evident in the deprecation of `Buffer()-without-new` and `fs.realpath()` discussions. The view seems to be that if we make _any_ changes in core that require the ecosystem to do _any_ work to update, then we've done something terrible, even if the breaking changes sitting in master have absolutely no impact on LTS or Current.

A key question is: what should we / can we do about this ?

One example of this is that because `Buffer()` without new now prints a deprecation warning, some tests in very popular modules are breaking because the test cases use `stderr` output to determine if the test failed or not. Use of `--no-warnings` or `--no-deprecation` would solve that issue, but that requires the module developer to do something to fix their test cases.

/cc @nodejs/ctc

**Comment by cjihrig** [comment]
I think this is just one of those things where there are different schools of thought. If we follow semver, and try to avoid drastic breaking changes, then landing things in `master`, but not v6 should be fine. The real problem is when breaking changes get through to the release lines even if they are accidental or just slip through the cracks.

**Comment by jasnell** [comment]
In general yes, but the `Buffer()-without-new` deprecation just landed in master and has not yet gone out into a release. It won't go into a release until v7 hits in October. The feedback from some module developers is that the change is unacceptable because it would require them to make modifications to their code, which they don't want to do.

**Comment by Trott** [comment]
I'm going to close this, but feel free to re-open it if you feel that's appropriate.
