### ISSUE TITLE
Request to move the Evangelism WG to CommComm

### ISSUE THREAD

**Issue by nebrius** [nodejs/CTC#145]
This is a request to move the Evangelism WG from being chartered under the CTC to being chartered under the Community Committee. This will be an administrative change only, the Evangelism WG will continue operating the same way that they do today.

I chatted with the evangelism folks at https://github.com/nodejs/evangelism/issues/294, and they're on board with moving to CommComm, so the next step is to get approval from the CTC.

Let me know if you have any questions or concerns!

**Comment by mcollina** [comment]
SGTM

**Comment by benjamingr** [comment]
I have a question - what is the Community Committee?

**Comment by addaleax** [comment]
@benjamingr Does the https://github.com/nodejs/community-committee README help? If not, feel free to ping the team (at nodejs/community-committee)

**Comment by MylesBorins** [comment]
Sgtm

**Comment by mcollina** [comment]
sgtm

**Comment by jasnell** [comment]
SGTM

**Comment by nebrius** [comment]
Thanks for the input everyone! Since this has been open a while, does the CTC have consensus on the issue? If so, I'll go ahead and start the conversation with CommComm to get signoff from the last group for the move, and then I'll submit some PRs to update docs!

**Comment by addaleax** [comment]
@nodejs/ctc @nodejs/tsc Let’s wait for objections for a couple of days, say, until Wednesday or so.

**Comment by Trott** [comment]
> @nodejs/ctc @nodejs/tsc Let’s wait for objections for a couple of days, say, until Wednesday or so.

No objections have been raised. This can move forward.
