### ISSUE TITLE
Add @bengl to @nodejs/security

### ISSUE THREAD

**Issue by bengl** [nodejs/CTC#149]
I'd like to be added to the @nodejs/security team. I couldn't find any defined process for inclusion in the team (and maybe that's something that needs to be addressed), so @jasnell suggested I should just ask here in an issue on CTC. I'm a Node.js collaborator working at a Node.js security company, and it would be nice if we could be as up-to-date as possible with the security-happenings and contribute to the best of our ability.

**Comment by jasnell** [comment]
ping @nodejs/ctc @nodejs/security ... definite +1 on this one. Any objections?

**Comment by mcollina** [comment]
Definitely +1.

**Comment by bnoordhuis** [comment]
@nodejs/security is already bigger than is responsible, IMO.  Access should be on a need-to-know basis, which, sorry @bengl, as far as I can see doesn't apply to you.

**Comment by rvagg** [comment]
I kind of agree with Ben here, sorry to say, we need to be a bit more careful in widening this particular tent. We already have a bunch of members that are deriving more value from inclusion than providing and what we need is clear additive value.

**Comment by jasnell** [comment]
> We already have a bunch of members that are deriving more value from inclusion than providing

Perhaps what we need, then, is to rotate some folks out in favor of bringing in new individuals who have a higher likelihood of participation.

**Comment by jbergstroem** [comment]
> @jasnell said:
> Perhaps what we need, then, is to rotate some folks out in favor of bringing in new individuals who have a higher likelihood of participation.

I agree with this. Lets try to find a size that CTC is comfortable with and slim it based on your suggestion?

**Comment by Trott** [comment]
This repo isn't active anymore, but perhaps @bengl would like to open this in the TSC repo? Either way, I'm going to close this.
