### ISSUE TITLE
Transfer i18n working groups to CommComm

### ISSUE THREAD

**Issue by jasnell** [nodejs/CTC#169]
All, see https://github.com/nodejs/community-committee/issues/114

I would like to propose that we transfer oversight of the many i18n working groups to the Community committee. These have never received any reasonable or effective attention from CTC or TSC and they fall under the mission of the CommComm already.

**Comment by Trott** [comment]
I support this.

**Comment by Trott** [comment]
TSC should take this up, IMO. Closing because this repo is obsolete but feel free to move the conversation to the TSC repo.
