### ISSUE TITLE
Outreachy Node.js Core project ideas for mentees

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/CTC#17]
#### Project ideas

To coordinate mentorship for the Outreachy and Node.js project effort, we are looking for Node.js core projects/issues that would be good for a mentee to work on for 3-4 months as part of learning to contribute to larger open source projects.

_What we'd love to see commented here is:_
- a Node.js project suggestion with description and potential issue(s) link(s)
- desired skills that a mentee would have in order to be successful on the suggested project(be kind!)
- ways for the mentee to prepare for the project prior to the term start

An example of this is what Franziska Hinkelmann from Google has offered for a project and mentoring:

> **Improve the vm module in Node.js core**
> The vm module is used in the Node.js command line and in DOM implementations, such as jsdom. Sadly, there are many open issues related to the module and it needs some love. Recent changes in V8, Node's JS engine, now make it possible to fix several of the issues and improve the vm code base significantly.
> 
> This project includes learning how to build and debug Node.js core, how the vm module is implemented, some Node internals about the global proxy, and how to use the V8 API. You will be coding in C++ and write tests in JavaScript.
> 
> No worries if you're not too familiar with these languages, a desire to learn and curiosity are much more important than a fixed skill set.
> 
> Mentor based in Europe.
> https://github.com/nodejs/node/issues/6283 

@nodejs/collaborators 

If you would like to instead offer your expertise as a supplemental mentor(our primary mentors have been confirmed), please mention it [here in the comments](https://github.com/nodejs/education/issues/7)

**Comment by MylesBorins** [comment]
Some projects I think could be cool
- improve the serial communication story in core
  -  currently there is a PR blocked on libuv that would help to allow serial support without a native module compilation
  - once that lands collaboration with the node-serial project would need to be done to get the proper interfaces into node /cc @reconbot
  - this is a huge win and decently scope.
  - It does involve planning / co-ordination across multiple projects
- Improve file watching 
  - I could be totally off on this one but I feel like the file watching implementation in libuv could be improved, but I could be totally off. /cc @saghul 
- collaborate on http2
  - I know @jasnell has broken ground on this but I'm not sure how much work has been done
- port of the debugger to new inspector api
  - someone has been working on a port but I cannot for the life of me remember who. /cc @ofrobots who was active in that thread

I wonder if @nodejs/build or @nodejs/benchmarking or @nodejs/post-mortem or @nodejs/diagnostics have ideas

**Comment by Trott** [comment]
Not sure these are appropriate for this or not, but they keep popping to
mind when I try to think of things:
- Dive deep on libuv and stdio issues and pull apart
  https://github.com/nodejs/node/issues/6980 and fix it. Would love to be
  able to close https://github.com/nodejs/node/issues/784 some time. Probably
  would help to work with some combination of @saghul, @bnoordhuis,
  @Fishrock123, someone else?
- Dive deep on the V8 tick processor stuff and fix all the
  `test/parallel/test-tick-processor-*` tests across all platforms. Probably
  would need to work with someone from @nodejs/v8 like @matthewloring and
  maybe folks from @nodejs/build as issues pop up on specific platforms.
- Dive deep on V8 inspector stuff and fix `test/inspector/test-inspector`
  on Windows. Probably would need to work with @eugeneo and maybe some
  Windows folks.
- Increase test coverage for `lib/_debugger.js` and `lib/_debug_agent.js`.
  Debugger tests are all over the place (figuratively) and coverage is
  spotty. They could benefit from some focused attention from someone. Hey, I
  might actually be a reasonably good mentor for this one!

**Comment by AndreasMadsen** [comment]
Some @nodejs/diagnostics projects:
- Unifying LTTNG, DTrace, ETW
  - https://github.com/nodejs/diagnostics/issues/10
  - not much work has been done here
- Creating API and integration for v8 trace_event.h
  - https://github.com/nodejs/diagnostics/issues/30
  - This is a very active project, I'm not sure how suitable it is for this program
- Async Wrap integration in [NAN](https://github.com/nodejs/nan)
  - No work has been done, and https://github.com/nodejs/node/pull/8531 does not yet expose the Embedder API.

**Comment by Trott** [comment]
Here I am trying plagiarizing...er, I mean, formatting one of mine more like @fhinkel's proposal:

**Improve test coverage and expand feature set for the Node.js debugger**

The Node.js debugger built-in debugger is minimal. Test coverage is spotty and there may be opportunities for expanded functionality. 

This project includes learning how to build Node.js core, how the debugger is implemented, and how testing is done in Node.js core. You will be coding in JavaScript and possibly a little C++.

Mentor based in North America (San Francisco).

**Comment by Trott** [comment]
Outreachy application deadline for mentors is Monday, so I think we can close this. Comment or re-open if I'm mistaken.
