### ISSUE TITLE
Requesting James to step down or be removed from the TSC

### ISSUE THREAD

**Issue by derekm** [nodejs/CTC#175]
I am officially asking that either James resign from the TSC voluntarily or a decision be made by the TSC to remove him on grounds that interactions with the community and with other members of the TSC and collaborator base have not been becoming of a TSC member.

Public backbiting within the Node.js community has no place and is abusive, disgusting and unbecoming.

Bad actors and trolls within the community need to be removed from the community.

**Comment by ljharb** [comment]
The CTC [no longer exists](https://github.com/nodejs/TSC/pull/317).

**Comment by derekm** [comment]
Thanks, @ljharb. I updated the language to refer to the TSC.

**Comment by benjamingr** [comment]
If you would like to file a report to the TSC please fill a report and send it to the relevant email.

Individual members are not discussed in public due to privacy concerns.
