### ISSUE TITLE
Moving CTC meeting notices and minutes to this repo

### ISSUE THREAD

**Issue by jasnell** [nodejs/CTC#21]
@nodejs/ctc: Can we please start posting the CTC meeting notices and minutes to this repo rather than to the main repository? The meeting minutes would be easier to consolidate here and generally just make much more sense being in this repo than in the main nodejs repository.

**Comment by williamkapke** [comment]
🎉   +1

(linking #18)

> Maybe have a transition period where an issue is also posted to node linking to the CTC issue?

**Comment by jasnell** [comment]
I'll open a PR shortly that moves the CTC minutes into this repo.

**Comment by joshgav** [comment]
This is now in place, so closing this issue.
