### ISSUE TITLE
Meeting Schedule

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#22]
We agreed to rotate meetings through the next one and then evaluate. So let's evaluate?
- Should we continue rotating meeting times?
- Daylight savings time may have already or will soon shift times by one hour for lots of people, and probably people's situations have changed anyway. **So if everyone could update the (private) Google Doc with their availability, that would help us determine if there might be better times to meet.**

Adding `ctc-agenda` label.

@nodejs/ctc

**Comment by bnoordhuis** [comment]
If anyone has trouble digging up the Google Doc link (I know I did), post a comment and I'll email it to you.

**Comment by mhdawson** [comment]
I could use the link

**Comment by Trott** [comment]
Here are the constraints I plan to use:
- Use only meeting times that have a median score of 3 or higher based on the data we have for current CTC members and the existing CTC nominee. (3 = estimated 80% or greater ability to attend at that time)
- All else being equal, favor the current meeting times over changing for the sake of changing.
- A CTC member should have at most one meeting time that they are likely to miss. In other words, for any individual, only one of the meeting times should be a score of less than 3.
- We're hoping to have three meeting times, but it may not be possible given the above constraints.

**Comment by Trott** [comment]
> A CTC member should have at most one meeting time that they are likely to miss. In other words, for any individual, only one of the meeting times should be a score of less than 3.

Currently, there is no way for this to happen with more than two times. We can have at most two meetings. Interestingly, the current time slots are no longer a pair of times that work together.

So, if you haven't updated the spreadsheet, especially if you may be more available than you were when you first filled it out, go update it!

<strike>In the meantime, I'm contemplating (if it's even possible!) having three times but having one time occur more frequently than the others such that nobody is a lock to miss more than (say) 40% of the meetings. This would be a slight improvement over the current situation where Rod (and maybe others) is a lock to miss 50% of the meetings.</strike> EDIT: Not possible.

**Comment by Trott** [comment]
It looks like the best option is status quo: keep rotating between 16:00 UTC and 20:00 UTC. (Sorry, Rod!) That would mean our next meeting would be at 16:00 UTC. For U.S folks at least, daylight savings ends this weekend, so that will now be 8AM Pacific Time and 11AM Eastern Time.

If someone's schedule will change radically, then it may be worth revisiting this. But barring that...

I'm changing the label on this from `ctc-agenda` to `ctc-review`. Can we get consensus on this? I'd like to leave it open until Monday, but hopefully be able to make a decision to go with it then. Here's the proposal:

| UTC-time | San Francisco | New York | Amsterdam | Moscow | Chennai | Tokyo | Sydney |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Wednesday, November 9, 2016 at 16:00:00 | Wed 8:00 AM | Wed 11:00 AM | Wed 5:00 PM | Wed 7:00 PM | Wed 9:30 PM | Thu 1:00 AM | Thu 3:00 AM * |
| Wednesday, November 16, 2016 at 20:00:00 | Wed 12:00 Noon | Wed 3:00 PM | Wed 9:00 PM | Wed 11:00 PM | Thu 1:30 AM | Thu 5:00 AM | Thu 7:00 AM * |
| Wednesday, November 23, 2016 at 16:00:00 | Wed 8:00 AM | Wed 11:00 AM | Wed 5:00 PM | Wed 7:00 PM | Wed 9:30 PM | Thu 1:00 AM | Thu 3:00 AM * |
| Wednesday, November 30, 2016 at 20:00:00 | Wed 12:00 Noon | Wed 3:00 PM | Wed 9:00 PM | Wed 11:00 PM | Thu 1:30 AM | Thu 5:00 AM | Thu 7:00 AM * |
| Wednesday, December 7, 2016 at 16:00:00 | Wed 8:00 AM | Wed 11:00 AM | Wed 5:00 PM | Wed 7:00 PM | Wed 9:30 PM | Thu 1:00 AM | Thu 3:00 AM * |
| Wednesday, December 14, 2016 at 20:00:00 | Wed 12:00 Noon | Wed 3:00 PM | Wed 9:00 PM | Wed 11:00 PM | Thu 1:30 AM | Thu 5:00 AM | Thu 7:00 AM * |
| Wednesday, December 21, 2016 at 16:00:00 | Wed 8:00 AM | Wed 11:00 AM | Wed 5:00 PM | Wed 7:00 PM | Wed 9:30 PM | Thu 1:00 AM | Thu 3:00 AM * |
| Wednesday, December 28, 2016 at 20:00:00 | Wed 12:00 Noon | Wed 3:00 PM | Wed 9:00 PM | Wed 11:00 PM | Thu 1:30 AM | Thu 5:00 AM | Thu 7:00 AM * |
| Wednesday, January 4, 2017 at 16:00:00 | Wed 8:00 AM | Wed 11:00 AM | Wed 5:00 PM | Wed 7:00 PM | Wed 9:30 PM | Thu 1:00 AM | Thu 3:00 AM * |

In January, we update the spreadsheet and check again to see if we can come up with something that might be better.

A few notes:
- November 23 is the day before a major holiday in the United States.
- November 30 is during Node Interactive North America.

Please consider leaving a lukewarm endorsements along the lines of: "This sounds tolerable. Grumble grumble but LGTM anyway."

**Comment by Trott** [comment]
It might be worthwhile experimenting with http://whenisgood.net/ to schedule meetings ad hoc if the some-people-are-guaranteed-to-only-be-able-to-make-50%-of-the-meetings-at-most issue is unacceptable.

**Comment by Trott** [comment]
@nodejs/ctc I think this is basically approved by default, but as a matter of process, can I get at least two LGTMs for the proposal to continue with the two meeting times we've been using for the next 9 meetings?

**Comment by Trott** [comment]
(Actually, I'm seeing a possible alternative thanks to a spreadsheet update by @misterdjules--thanks for keeping the sheet up to date! It helps a lot! I don't want to muddy the waters on this quite yet. I'd like to get this approved so we at least have a meeting time for this week and next week, and then I'll throw in the curveball alternative and we can decide if we like it better or not.)

**Comment by thefourtheye** [comment]
LGTM if @rvagg is okay with this, as I am one of the few CTC members who is benefited because of this rotation and Rod is the one least benefited :(

**Comment by MylesBorins** [comment]
LGTM

**Comment by evanlucas** [comment]
LGTM

**Comment by Trott** [comment]
Thanks, everyone! Alternative suggestion coming soon, but for the moment, this is the schedule.
