### ISSUE TITLE
CTC moderator

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#23]
My reading of [GOVERNANCE.md](https://github.com/nodejs/node/blob/45a716c9687849b7ade2ce01f2421c8f791f907c/GOVERNANCE.md) is that the meeting moderator does not need to be a CTC member.

I would be interested in trying out having one of our observers or even a new observer (perhaps William Kapke if he has the time and inclination?) act as the moderator.

Thoughts?

@nodejs/ctc

**Comment by Fishrock123** [comment]
I would love to get more interested people to rotate in such a role.

**Comment by rvagg** [comment]
are we talking about a meeting chair here or something different?

**Comment by Trott** [comment]
> are we talking about a meeting chair here or something different?

Meeting chair. GOVERNANCE.md refers to it as a moderator.

**Comment by mhdawson** [comment]
I'm happy to volunteer to act as moderator on a rotating basis, I'm also ok with observers acting as the moderator.

**Comment by Trott** [comment]
@mhdawson Timely! Assuming we go with the times I proposed yesterday, Rod cannot come to the next meeting and (due to daylight savings ending) I likely won't make it either.

**Comment by jasnell** [comment]
Does this need to remain open?

**Comment by Trott** [comment]
> Does this need to remain open?

I'd like to have more conversation around this, but we can close this issue and I can open a new one or re-open this one when I'm actually ready to have that conversation.
