### ISSUE TITLE
Reduce the single point of failure for livestreaming meetings.

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/CTC#24]
Given that we have too any participants on many CTC and TSC calls for Hangouts on Air, we use different conference software and stream manually to youtube.

I recently wrote documents into the TSC repo for how to use an Encoder (in this case, [OBS](https://obsproject.com/)) to do this. They can be found at [TSC/streaming/](https://github.com/nodejs/TSC/tree/master/Streaming).

@nodejs/ctc While my setup is particularly good for streaming and I may be able to do so 90% of the time I'd like at least 2 other people who *can* without major preparations.

The main catch is that macOS machines do not allow desktop audio capture by default, and as such require either custom, or paid drivers (such as [Loopback](https://www.rogueamoeba.com/loopback/)). Linux and Windows do not have any such issues.

I typically run the stream from a second Windows computer, but you can do it with a single computer just noting the above caveat.

**Comment by Fishrock123** [comment]
ping @nodejs/ctc we **need** someone to be able to do this as backup.

**Comment by williamkapke** [comment]
@Fishrock123 I'm interested in helping out with this. It's on my todo list-- which I'm looking to tackle after Node Interactive Austin.

**Comment by Fishrock123** [comment]
Ok, that may be good backup for TSC meetings but I think we'll still need one more for the CTC.

**Comment by williamkapke** [comment]
Someone on the CTC would be best for CTC calls- but I usually tune-in to the Live Stream and could jump on as an Observer if needed. (Plan `C` lol)

**Comment by Trott** [comment]
Reminder/bump for @williamkapke and @Fishrock123 (and anyone else interested in this): Node Interactive is going on, @Fishrock123 is here, might be a good time to meet up with @Fishrock123 and make this happen!

**Comment by Fishrock123** [comment]
That never happened... :/

@williamkapke please let me know if you need any help setting up for TSC meetings.

**Comment by thefourtheye** [comment]
I installed OBS Studio. I need to get YouTube Stream Key now. @mikeal Can you help me with this?

**Comment by Fishrock123** [comment]
@thefourtheye Did you follow the rest of the setup [in the guide](https://github.com/nodejs/TSC/blob/master/Streaming/Setting-Up-Open-Brodcaster-Software.md)?

I suggest getting the stream key from your personal youtube first to test it. :)

**Comment by Trott** [comment]
Closing this as a bit of cleanup for the CTC repo but feel free to re-open in the TSC repo.
