### ISSUE TITLE
Move more CTC things to this repo?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/CTC#25]
As we all know, the Node repo is pretty high volume for issues and changes. I know I have a hard time keeping up with all of them.

I'm wondering if we can move some(all?) of the governance documents to this repo to help keep a separation between documentation and code.

I'm happy to do a PR if there is interest.

**Comment by joshgav** [comment]
@jasnell planned to move meeting notes over from the main repo to here too. Makes sense to limit the surface area of the main repo I think.

**Comment by Trott** [comment]
Minutes and meeting announcements have been moved. I'm going to close this but feel free to re-open (or open a separate issue) if anyone wants to pursue it further.
