### ISSUE TITLE
A new New CTC Meeting Schedule Proposal

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#29]
All times are in UTC.

Currently, we are rotating between 16:00 and 20:00.  This means that 50% of the meetings are at bad times for Shigeki, Sakthipriyan, Rod, Julien, Anna, and me. 

If we keep half of our meetings at 20:00 but rotate the other two meetings between 16:00 and midnight, it looks like this:

* 50% of the meetings are still bad for Shigeki, Sakthipriyan, and Anna (and in fact, this is *slightly* worse for Anna than the status quo)
* However, there are now only 25% bad times for Rod, Julien, and me
* The following people also see an increase from 0% bad times to 25% bad times: Ben, Nikita, Colin, Michael Dawson, and Trevor

So, yeah, trade-offs.

An obvious question might be "Why not each meeting exactly one third of the time?" The answer is that because then there will be a CTC member for whom 2/3 of the meeting times will be bad. I don't think we want to have more than 50% bad times for anyone, if it's something that we can avoid.

So, for comparison, here's the current month of November:

|  UTC-time | San Francisco  | New York | Amsterdam | Moscow | Chennai | Tokyo | Sydney |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------|
| Wednesday, November 9, 2016 at 16:00:00 |	Wed 8:00 AM|	Wed 11:00 AM|	Wed 5:00 PM	|Wed 7:00 PM	|Wed 9:30 PM	|Thu 1:00 AM	|Thu 3:00 AM *|
|Wednesday, November 16, 2016 at 20:00:00|	Wed 12:00 Noon|	Wed 3:00 PM	|Wed 9:00 PM	|Wed 11:00 PM|	Thu 1:30 AM|	Thu 5:00 AM|	Thu 7:00 AM *|
|Wednesday, November 23, 2016 at 16:00:00	|Wed 8:00 AM	|Wed 11:00 AM|	Wed 5:00 PM|	Wed 7:00 PM	|Wed 9:30 PM	|Thu 1:00 AM	|Thu 3:00 AM *|
|Wednesday, November 30, 2016 at 20:00:00|	Wed 12:00 Noon|	Wed 3:00 PM	|Wed 9:00 PM	|Wed 11:00 PM|	Thu 1:30 AM|	Thu 5:00 AM	|Thu 7:00 AM *|

And here's what it might look like if we switch to this proposal. (Only November 23 is different.)

|  UTC-time | San Francisco  | New York | Amsterdam | Moscow | Chennai | Tokyo | Sydney |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------|
| Wednesday, November 9, 2016 at 16:00:00 |	Wed 8:00 AM|	Wed 11:00 AM|	Wed 5:00 PM	|Wed 7:00 PM	|Wed 9:30 PM	|Thu 1:00 AM	|Thu 3:00 AM *|
|Wednesday, November 16, 2016 at 20:00:00|	Wed 12:00 Noon|	Wed 3:00 PM	|Wed 9:00 PM	|Wed 11:00 PM|	Thu 1:30 AM|	Thu 5:00 AM|	Thu 7:00 AM *|
|Wednesday, November 23, 2016 at 00:00:00|	Tue 4:00 PM|	Tue 7:00 PM|	Wed 1:00 AM|	Wed 3:00 AM|	Wed 5:30 AM|	Wed 9:00 AM|	Wed 11:00 AM *|
|Wednesday, November 30, 2016 at 20:00:00|	Wed 12:00 Noon|	Wed 3:00 PM	|Wed 9:00 PM	|Wed 11:00 PM|	Thu 1:30 AM|	Thu 5:00 AM	|Thu 7:00 AM *|

Thoughts?

**Comment by rvagg** [comment]
I'd like to hear from @addaleax and @thefourtheye in particular here, it's an improvement for me, yay, but that shift looks like it has the potential to be uncomfortable enough to have multiple people regularly opting out because it's pushing just a little too far and we end up not improving the situation at all.

**Comment by addaleax** [comment]
I think these times would be okay for me… midnight UTC might really be getting a bit late but as long as it’s only once a month, it sounds doable

**Comment by thefourtheye** [comment]
I am okay with this.

**Comment by mhdawson** [comment]
I'm good with the new schedule, I may not be able to make the off meeting, but still can't complain about the times for me as they still look good compared to many of the rest of the team.

**Comment by Fishrock123** [comment]
So uh, do we have to ratify this? What time will tomorrow's meeting be at?

**Comment by trevnorris** [comment]
If we're doing a three week rotation, this'll mean it can't align w/ the month. i.e. first Wed of the month is always 1600 UTC.

Please, give me fixed times on fixed intervals that I can place in my calendar. I don't like the idea of needing to add a meeting to my calendar for every CTC meeting we have.

**Comment by bnoordhuis** [comment]
Alternative proposal for November 23: UTC 0500.  Yes, it means New Yorkians will have to stay up late but it's much more palatable for the other six timezones:

| UTC | SF | NY | A'dam | Moscow | Chennai | Tokyo | Sydney |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 2016-11-23 05:00 | Tue 21:00 | Wed 00:00 | Wed 06:00 | Wed 09:00 | Wed 10:30 | Wed 14:00 | Wed 16:00 |

**Comment by Trott** [comment]
@bnoordhuis There are only 7 CTC members who indicated that they will be able to typically make a meeting at that time (giving it a "3" or higher).  And there are 6 CTC members who indicated they can never make that time (giving it a score of "0").

For comparison, the proposed UTC 0:00 = 12 CTC members who can typically make it and only 3 CTC members who can never make it.

I'm open to trying to work a fourth time into the mix if it can help us get everyone under 50% expected absences. How about we stick with what I suggested above for November and December and we make the <50% expected absences (and thus at least a fourth time) the goal for a proposal that starts in January?

**Comment by Trott** [comment]
FWIW I've added a row for @targos in the spreadsheet and asked them to fill in their row. For what it's worth, that should help increase the weighting for European time zones ever so slightly.

**Comment by Trott** [comment]
@trevnorris If this gets the OK, you'd need three recurring meetings: The 20:00 meeting would be every two weeks. The other two times would be every four weeks.

Week 1, 3, 5, 7, 9, etc.: 20:00
Week 2, 6, 10 etc.: 16:00
Week 4, 8, 12 etc.: 00:00

I'd be willing to maintain Google Calendar and/or Outlook meeting invitations if it's the difference between this being no problem for someone and it being a huge headache.

**Comment by Trott** [comment]
Adding `ctc-agenda` label.

**Comment by bnoordhuis** [comment]
> There are only 7 CTC members who indicated that they will be able to typically make a meeting at that time (giving it a "3" or higher). And there are 6 CTC members who indicated they can never make that time (giving it a score of "0").

Yes, but those six are all Americans as far as I can tell.  I can understand they don't want to give up their evenings but right now it's the people in other time zones that get to sacrifice their nights over and over again.  There needs to be a little give and take.

Note I'm not advocating it because it's convenient for me - it's unholy early in the morning - but it genuinely seems like the best time for the largest CTC subset.

**Comment by Trott** [comment]
> Yes, but those six are all Americans as far as I can tell. 

If "Americans" refers to North Americans (so it includes Canadians), then yes. Nonetheless, of the 3 at 00:00, 2 of them are in North America. So the difference (by this metric at least) is not as stark as it could be.

> right now it's the people in other time zones that get to sacrifice their nights over and over again. There needs to be a little give and take.

That's a valid point. 00:00 is 7PM in New York, but (unlike meeting times in other time zones) that is not going to deprive anyone of a full night of sleep.

The more I'm looking at this, the more I'm fine with either time being the third meeting time. I'm also inclined to go back and stare at the spreadsheet some more to see if I can concoct a four-meeting rotation that would be more equitably awful/good for everyone.

**Comment by Trott** [comment]
I nerded out a little on this and wrote some code to normalize everyone's scores and then  calculate standard deviations of scores across individuals so as to identify combinations of times that would be the most equitable.

If we want to keep 16:00 and 20:00 but add a third time, the most equitable is indeed as Ben proposed: 05:00 16:00 20:00. My proposal isn't even in the top 5.

**Comment by Trott** [comment]
EDIT: deleted first part of comment because:

I'm probably dooming us to indecision by presenting far too many options. I'll stop now.

**Comment by Trott** [comment]
OK, so, do we want to try the 5:00AM time next week [per Ben's proposal above](https://github.com/nodejs/CTC/issues/29#issuecomment-259484229)?

Or stick with the two times for now because everyone is already confused enough?

If we want to try the new time, I can volunteer to be particularly persistent in messaging to CTC members about the change.

**Comment by Trott** [comment]
I'm going to remove the ctc-agenda label for now and try again for January. Until then (unless someone else picks up the issue, which if you feel strongly that we should add at least a third meeting time, please do!!!), we stick with the two meeting times we have...

**Comment by ChALkeR** [comment]
@bnoordhuis, in your proposal, Moscow time should be 8:00, not 9:00.
