### ISSUE TITLE
Intl WG Status?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/CTC#42]
At Collab Summit today, we ran down then list of WGs and had a status update of how things are going as a Working Group and if it still represents the intended goal.

No one was able to provide an update on Intl.

Could someone from Intl please update?
Does it need to remain a charted Working Group or can it be just a Team?

/cc
@nodejs/intl 

Caridy Patiño (@caridy)
James Snell (@jasnell)
Kevin Jose Martin (@KevinMartin)
Michael Dawson (@mhdawson)
Rafael Xavier de Souza (@rxaviers)
Rick Waldron (@rwaldron)
Steven Atkin (@stevenatkin)
Steven R. Loomis (@srl295)

**Comment by williamkapke** [comment]
@srl295 I think someone at the Collab Summit pointed the finger directly at you on this hah.

**Comment by srl295** [comment]
Yes. We are trying to restart monthly calls in the new year.

**Comment by Trott** [comment]
Closing this as a bit of cleanup for the CTC repo but feel free to re-open in the TSC repo.
