### ISSUE TITLE
My notes from the collaborator summit

### ISSUE THREAD

**Issue by mcollina** [nodejs/CTC#44]
Hi Folks,

I took some notes during the collaborator summit, and some of you showed interest in me publishing it here.

### VM neutrality

![vm-neutrality](https://cloud.githubusercontent.com/assets/52195/20989809/5830119a-bcd6-11e6-92dd-d758258947c3.jpeg)

### Deprecation

![deprecation](https://cloud.githubusercontent.com/assets/52195/20989814/624e8ef4-bcd6-11e6-80dd-31f2c426b532.jpeg)

![deprecation-2](https://cloud.githubusercontent.com/assets/52195/20989827/7009ed86-bcd6-11e6-81e9-c72ebf156108.jpeg)

### Security WG

![security-policy-wg](https://cloud.githubusercontent.com/assets/52195/20989835/773a6d7e-bcd6-11e6-97a4-d09f7db09d77.jpeg)

cc @nebrius @jasnell

**Comment by jasnell** [comment]
These are awesome... thanks for posting. Going to go ahead and close the issue but great to have these
