### ISSUE TITLE
Growing the group of releasers

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/CTC#48]
I think it's high time we add a couple more people who can do Node.js releases.

Contrary to common (I assume from past interactions) belief, you don't need to be on the CTC to be a releaser. (Although we'd probably want you to be a collaborator.)

As such I'd actually prefer to get one or more non-CTC collaborators to be able to do releases.

cc @nodejs/collaborators 

Note: doing releases _is_ a bit time consuming, but you won't be _required_ to do them frequently, only encouraged to do them here and there. :)

(It's really up to you most times, create a release proposal issue and run with it.)

---

In fact, the best way to start if you are interested would be to propose the next v7 (Current) release! (Anyone can do this part actually! See near the bottom.)

To do so, create a `v7.3.0-proposal` branch (**on the main repo**)  off of `v7.x-staging` and create a PR with it stating the version you'd like to propose (like v7.3.0) along with the proposed release date (usually Tuesdays or Wednesdays, never weekends).

If you're not a collaborator and would still like to do this part, you can create an issue on [nodejs/node](https://github.com/nodejs/node) with the proposed version, date, and a list of markdown formatted commits made from [`changelog-maker`](https://www.npmjs.com/package/changelog-maker) or [`branch-diff`](https://www.npmjs.com/package/branch-diff) (by difference between the `head` of v7.x-staging and the last 7.x release).

**Comment by gibfahn** [comment]
I'm definitely interested in being able to do releases.

**Comment by jasnell** [comment]
Absolutely would be a good thing. Not sure how we should go about it but I think pairing up potential new releasers to shadow while a new release is being prepared is a great way to start. The next release I'll be working on it Node.js 8 starting in March. If anyone would like to help along with that process to learn the steps please let me know.

**Comment by Fishrock123** [comment]
> Absolutely would be a good thing. Not sure how we should go about it but I think pairing up potential new releasers to shadow while a new release is being prepared is a great way to start.

I think this is usually what we did in the past and is pretty much required IMO.

The release steps are non-trival and plenty can still go wrong, having immediate backup at first is absolutely critical.

**Comment by jasnell** [comment]
@gibfahn ... if you'd like, you can shadow me while I begin to prepare the v8 major release starting in March

**Comment by mhdawson** [comment]
+1 from me.

**Comment by mhdawson** [comment]
In weekly CTC meeting, formal vote.  With Michael Dawson, Colin Ihrig, Evan Lucas, James Snell, Rich Trott, Ali Sheikh +1 to extending the invitations to @italoacasas  and @gibfahn and giving them access to to be able to releases.

@nodejs/ctc All please add your votes.

**Comment by italoacasas** [comment]
If everyone agrees in the vote, yes I would like to continue helping with the releases.

**Comment by gibfahn** [comment]
@jasnell that'd be great, I'd love to be able to shadow you. Thanks!

**Comment by targos** [comment]
+1

**Comment by Trott** [comment]
10 +1's at today's CTC meeting along with the +1's from @targos and @mhdawson above put this at 12 votes which is a majority, so it passes. The vote was on extending an invitation to Italo and Gibson and not any changes to policy or anything like that. So, I think @Fishrock123 or one of the other existing releasers can take it from here. I'll remove the `ctc-agenda` label.

**Comment by gibfahn** [comment]
>@gibfahn ... if you'd like, you can shadow me while I begin to prepare the v8 major release starting in March

@jasnell when will you start preparing for this? Still keen to shadow (and hopefully help out).

**Comment by Trott** [comment]
Closing this as a bit of cleanup for the CTC repo but feel free to re-open in the TSC repo or another appropriate repo.
