### ISSUE TITLE
CTC Meeting Times for 2017

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#49]
@nodejs/ctc 

Feedback so far (please correct if I've misinterpreted you!):

Yes (13): @Trott @bnoordhuis @addaleax @rvagg @thefourtheye @TheAlphaNerd @targos @cjihrig @evanlucas @ChALkeR @indutny @jasnell @mscdex 
No (0):
Abstain (0):
Not yet commented (7): @chrisdickinson  @fishrock123  @mhdawson @misterdjules @ofrobots @shigeki @trevnorris

We need to get at least one more meeting time into the rotation IMO. The current rotation between two times means that Rod and Sakthipriyan (and probably Shigeki too) are basically guaranteed to miss at least half our meetings. By adding one more meeting time, we can make it (at least in theory) so that everyone can attend more than half the meetings. The downside is that it would need to be a meeting time that many people would find very difficult. 

In other words, we'd trade having a small number of people who can't make ~50% of the meetings for a larger number of people who can't make ~33% of the meetings. I think that's a worthwhile trade. Spread the inconvenience out more equitably and all that.

Ben made some persuasive arguments for 05:00 UTC. Looking at the data in the spreadsheet we all filled out, it does seem that is the most equitable time.<sup>*</sup> 

Here is how that plays out across some relevant time zones, along with the two existing times:

|  UTC | SF  | NY | DE/NL | Moscow | Chennai | JP | Sydney |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 05:00 |	9 PM |	12 AM (midnight) |	 6 AM	|8 AM	|10:30 AM	|2 PM	|4 PM|
| 16:00 |	8 AM|	11 AM|	 5 PM	| 7 PM	| 9:30 PM	| 1 AM	| 3 AM |
| 20:00|	12 PM (noon) |	3 PM	| 9 PM	| 11 PM|	1:30 AM|	5 AM|	7 AM |

I'm up for giving this rotation a try for three or six months and see how it works. What does everyone else think?

<sup>*</sup> To calculate "equitable", I checked the standard deviation of preferences for everyone across the three resulting meeting times. Adding 05:00 to the existing two meeting times resulted in the lowest standard deviation of any possible third time, which means that it results in a set of meeting times that are the closest to equally convenient/inconvenient for everyone.

**Comment by ChALkeR** [comment]
My schedule for 2017 would probably change, and I don't yet know how exactly would it look.
I will update my row in the «meeting time options» table accordingly when I will have more information.

*Upd:* I expect all three proposed time slots to be green for me, though.

**Comment by bnoordhuis** [comment]
I'm +1 on the proposed times.

**Comment by Trott** [comment]
In email, I confirmed that the new time works for @rvagg and @thefourtheye. And @ChALkeR and @bnoordhuis have left favorable comments here. 

It would be good to get feedback from others who are not in the Americas. So that would be @addaleax @shigeki @targos

**Comment by addaleax** [comment]
I’m pretty certain I’d be missing most of or all of the meetings at UTC 05:00, but I agree that it’s worthwhile if it enables others to attend more frequently. So, +1 from me.

**Comment by targos** [comment]
+1

**Comment by Trott** [comment]
If I'm reading this right, it has a +1 or similar from 7 of the 20 CTC folks and no comment so far from others. I'll put this on the agenda for this week's meeting to hopefully make it official. If anyone has concerns about trying out this third meeting time, please comment!

List of people this has a +1 or +1-ish from: @Trott @rvagg @thefourtheye @ChALkeR @bnoordhuis @addaleax @targos

**Comment by MylesBorins** [comment]
I'm +1 on adding the new time. Would you be able to put a list of votes at the top @trott?

**Comment by Trott** [comment]
> Would you be able to put a list of votes at the top @trott?

Sure, done.

**Comment by evanlucas** [comment]
I think it makes sense to add an additional meeting time. +1 from me.

**Comment by ofrobots** [comment]
+1 as well

**Comment by indutny** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by mscdex** [comment]
+1

**Comment by mhdawson** [comment]
+1
