### ISSUE TITLE
Buffer constructor: commit to deprecating

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#87]
This is one of several votes started in today's @nodejs/ctc meeting.

This proposition can be stated as: Should the CTC announce now that Buffer constructor (or a subset of Buffer constructor usage)  is going to be runtime-deprecated at some future point, possibly without specifying that future point now?

Vote YES if you believe the CTC should make such an announcement now.

Vote NO if you believe the CTC should not make such an announcement now. 

YES: @chalker, @targos, @mscdex, @fhinkel

NO: @evanlucas, @addaleax, @jasnell, @ofrobots, @Fishrock123, @mhdawson, @cjihrig, @trott, @mylesborins, @misterdjules

ABSTAIN: @trevnorris

(I have updated my own vote since the meeting from "abstain" to "no".)

If you are a CTC member and have not yet voted, please indicate your vote in a comment below. We need to get resolution on this before we can move to the next vote, as there are individuals whose views on the desirability of some solutions are based on whether or not we are committed to a runtime deprecation in the future.

**Comment by misterdjules** [comment]
My vote is no.

**Comment by Trott** [comment]
With 4 yes votes, 10 no votes, and 1 abstention, this can be called as a NO at this point. Thanks, everyone. (I will note, for clarity for observers, that this doesn't mean we can't decide at a later date that we want to do this at that time.)
