### ISSUE TITLE
Buffer constructor: opt-in deprecation flag?

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#88]
@nodejs/ctc Next vote that was started at today's meeting is about whether we want an opt-in deprecation flag in version 8.0.0 of Node.js. There is a pull request for this but it seems to have reached an impasse in the conversation about it. https://github.com/nodejs/node/pull/11968

Vote YES if you endorse an opt-in deprecation flag in version 8.0.0. Although it could be used for other things, it will initially be used just for the Buffer constructor deprecation.

Vote NO if you oppose an opt-in deprecation flag in version 8.0.0.

YES:  @chalker, @ofrobots, @targos, @trott, @addaleax, @mhdawson,  @jasnell, @indutny 

NO: @cjihrig, @evanlucas, @mscdex, @fhinkel, @bnoordhuis 

ABSTAIN: @fishrock123, @trevnorris, @mylesborins, @misterdjules, @shigeki 

If your vote is not recorded above, please indicate your vote by commenting below. Thanks!

**Comment by indutny** [comment]
NO

**Comment by shigeki** [comment]
ABSTAIN

**Comment by bnoordhuis** [comment]
<sup>YES</sup>

**Comment by Trott** [comment]
With 8 YES votes, 5 NO votes, and 5 abstentions, this can be called: YES.

Thanks, everyone.
