### ISSUE TITLE
Buffer constructor: random-fill in Node.js 8.0.0?

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#90]
@nodejs/ctc Next vote that was started in the CTC meeting. If you are not listed below (or if your vote has changed or been recorded incorrectly), please comment! Thanks!

Should we random-fill in Node.js 8.0.0?

YES: @addaleax, @cjihrig, @targos, @fhinkel

NO: @mscdex, @ChALkeR, @indutny, @jasnell, @mylesborins, @shigeki, @misterdjules, @trevnorris, @rvagg, @thefourtheye 

ABSTAIN: @trott, @Fishrock123, @ofrobots, @evanlucas 

MY VOTE DEPENDS ON WHETHER OR NOT WE BACKPORT AND/OR WHICH RELEASE LINES WE BACKPORT TO:

There is a separate issue for the question of whether we zero-fill. If both pass and there's not consensus over which one to do, we'll have another vote.

**Comment by indutny** [comment]
NO

**Comment by jasnell** [comment]
No (my vote is for zero-fill in Node.js 8.0.0)

**Comment by MylesBorins** [comment]
what james said

**Comment by Fishrock123** [comment]
abstain (favor zero-fill)

**Comment by Fishrock123** [comment]
abstain (favor zero-fill)

**Comment by ofrobots** [comment]
Abstain (favour zero fill).

**Comment by evanlucas** [comment]
Abstain (favor zero fill)

**Comment by shigeki** [comment]
No

**Comment by misterdjules** [comment]
My vote is no.

**Comment by trevnorris** [comment]
nope

**Comment by rvagg** [comment]
no

**Comment by addaleax** [comment]
If I’m counting correctly this has 9 No votes and 4 abstentions, which means that this can be closed with “No” as the result.

**Comment by thefourtheye** [comment]
No - Zero Fill.
