### ISSUE TITLE
Buffer constructor: should we backport zero-filling?

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#91]
Barring multiple last-minute vote changes, we're going to be zero-filling the Buffer constructor in Node.js 8.0.0

Final question from the set of votes held at this week's CTC meeting: Do we backport this change?

No one expressed approval for the idea of backporting to some release lines but not all. So I'm going to assume we're talking about backporting to all currently-supported release lines: 7.x, 6.x, and 4.x. If you favor backporting only to some release lines, leave a comment and we'll figure out how to account for it.

YES: @Fishrock123 @trott @jasnell @mylesborins @trevnorris 

NO: @mscdex @mhdawson @evanlucas @fhinkel @thefourtheye @misterdjules @rvagg @indutny

ABSTAIN: @targos @cjihrig @addaleax @ofrobots @ChALkeR @shigeki

**Comment by Trott** [comment]
@nodejs/ctc If you have not been accounted for above, please leave your vote or abstention in a comment. Thanks.

**Comment by thefourtheye** [comment]
For example, if we backport to 6.x.y, the servers running older versions of 6 will not get this change.  And when they eventually upgrade, this would be a surprising behavioural change. So, voting no.

**Comment by misterdjules** [comment]
My vote is no.

**Comment by shigeki** [comment]
ABSTAIN

**Comment by trevnorris** [comment]
sure.

**Comment by ChALkeR** [comment]
@trevnorris, just to be sure — is that a YES?

**Comment by rvagg** [comment]
No, partly because it's a surprising behaviour change and is technical breaking but also because 4 is in maintenance as of today and this is not "critical".

**Comment by Trott** [comment]
I think we can call this as rejected, or at least not passing.

6 abstentions means that it needs 8 YES votes to pass.

Even if both the remaining outstanding votes (from @bnoordhuis and @indutny) come in as YES, it's a 7-YES/7-NO tie and the proposal does not pass.

I will note that we can still choose to backport this at a later date, or someone can raise a proposal (right now or later) to backport only to some lines.

But for the moment: We will not backport this behavior.

(Feel free to re-open if you think my vote-counting is in error or if anyone is switching from ABSTAIN or NO to YES.)

**Comment by Trott** [comment]
I do want to comment how nice it is that votes are not divided along company lines or anything like that.

Three NodeSource employees can vote. Two of them voted yes and one of them voted no.

Three Google employees can vote. One voted yes, one voted no, and one abstained.

I wouldn't expect any less than people to vote their consciences and all that, but it's nice to see it manifest anyway.

**Comment by indutny** [comment]
NO
