### ISSUE TITLE
Emeritus status for CTC

### ISSUE THREAD

**Issue by Trott** [nodejs/CTC#92]
I found out recently that Ember.js has an emeritus status for core team members who are no longer active. Maybe it's an informal thing as a quick web search didn't turn much up. But the point is it got me thinking...

Perhaps having an emeritus status for CTC (and maybe TSC too?) would help with situations where people are inactive. Right now, we don't have anyone whose activity is so low that I'd want to suggest we use this. But that makes it the perfect time to discuss it, because it's not about any particular individual; it's about our process.

Someone who was emeritus would be listed as such in the README. But otherwise, they would be indistinguishable from any other Collaborator. This is mostly about psychology and appearances, but I do think that it might ease the process of coming to terms with leaving. And it seems like it's just a nice and respectful thing to do.

One potential issue is whether or not someone who rage-quits under tense circumstances should be granted emeritus or not. But those details can be worked out once we have agreement that this overall is A Good Idea or that it is Not A Good Idea.

@nodejs/ctc

**Comment by bnoordhuis** [comment]
Sounds like A Good Idea to me.

**Comment by jasnell** [comment]
The only question I would have on this is what happens when an Emeritus member does return to become more active again? Is their voting position on the CTC/TSC restored or are they simply Collaborators still or ...?

**Comment by bnoordhuis** [comment]
Seems only fair they need to be voted in again at the CTC's discretion.

**Comment by Trott** [comment]
Yeah, what @bnoordhuis said. I don't think anyone who leaves active CTC should be guaranteed anything in the future, but I suspect that anyone who leaves under relatively uncontroversial circumstances is likely (but again, not guaranteed) to be welcomed back if they find themselves getting active again and wanting back on. On the other hand, someone who leaves under a cloud of some kind may find it more challenging, but it's ultimately up to the CTC to decide its own membership. I don't think there should be any rules (at least not related to Emeritus status) that curtail that self-determination.

**Comment by mhdawson** [comment]
Sounds reasonable to me as well based on the discussion so far.  Emeritus status would mostly be a "thank you" for the work done without any special privileges attached except that you can say that you have it.

**Comment by cjihrig** [comment]
We should use some of the Foundation's money to set them up with a pension. Also this idea, SGTM.

**Comment by Trott** [comment]
I guess I'll also add that if we don't like "emeritus", we can also use "alumnus". /shrug

**Comment by Trott** [comment]
Closed by https://github.com/nodejs/node/issues/13232
