### ISSUE TITLE
Why do people need/want to be org owners

### ISSUE THREAD

**Issue by mhdawson** [nodejs/CTC#97]
There is discussion about who should be org owners under: [125](https://github.com/nodejs/TSC/issues/125)

Part of the discussion is around what having CTC/TSC members be org owners enables in our day to day workflows

Some of things I know it has allowed me to do when necessary:

* inviting people to join the org
* create teams
* create repos
* add tags to issues across the repos

From discussion in the last TSC meeting we wanted to get info from the CTC as to:

* what kinds of activities do you believe you need to be an org owner in order to complete.
* if being an org owner was opt-in for CTC members, would you opt in ?

**Comment by Trott** [comment]
> if being an org owner was opt-in for CTC members, would you opt in ?

Yes.

**Comment by targos** [comment]
I think any organisation member can create new teams and repos.

**Comment by bnoordhuis** [comment]
> what kinds of activities do you believe you need to be an org owner in order to complete.

Your list + blocking users + access to the audit log.

> if being an org owner was opt-in for CTC members, would you opt in ?

Yes.

**Comment by targos** [comment]
I like being notified when a repo is created in the org. Only owners get that (if they have enabled automatic watching).

**Comment by cjihrig** [comment]
> if being an org owner was opt-in for CTC members, would you opt in ?

Yes

**Comment by Trott** [comment]
I also use it to audit the list of Collaborators to make sure they're all using 2FA. (You don't get to see if they're using 2FA if you're not an Owner, I don't think.)

**Comment by evanlucas** [comment]
> if being an org owner was opt-in for CTC members, would you opt in ?

I would for many of the reasons above.

**Comment by bnoordhuis** [comment]
Seems the discussion ran its course.  Closing but feel free to reopen.
